# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Valedido - Web Design & Development
email: valentino.didomenico@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Il sito internet di Valentino Di Domenico (in arte Valedido) è il luogo dove trovare qualche consiglio su come sviluppare un sito internet che sia semplice ed intuitivo da usare, che riesca a raggiungere gli internauti (vedi utenti) con il proprio messaggio e che esprima i propri valori. Senza fretta ma senza sosta, perché anche nel Web tutto scorre.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://valedido.github.io" # the base hostname & protocol for your site
twitter_username: valedido_91
github_username:  valedido

# Build settings
markdown: kramdown
